config/routes.rb
Unconf::Application.routes.draw do
  root to: "conferences#index"

  resources :conferences, only: [:new, :create, :show] do
    resources :events, only: [:new, :create]
  end
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :events
  # @conference.events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :conference
  # @event.conference
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  def index
    @conferences = Conference.all
  end
  
  def new
    @conference = Conference.new
  end

  def create
    conference_params = params.require(:conference).permit(:title, :desc, :starts_at, :ends_at)
    @conference = Conference.new(conference_params)

    if @conference.save
      redirect_to :root
    else
      # handle errors
    end
  end

  def show
    @conference = Conference.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @conference = Conference.find(params[:conference_id])
    @event = Event.new
  end

  def create
    @conference = Conference.find(params[:conference_id])
    
    event_params = params.require(:event).permit(:title, :desc, :speaker, :location) #:starts_at, :duration
    @event = @conference.events.new(event_params)

    if @event.save
      redirect_to @conference
    else
      # handle errors
    end
  end

  def edit
  end

  def delete
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/conferences/index.html.erb
<div class="jumbotron">
  <div class="containter text-center">
    <h1>UnConf</h1>
    <%= link_to "New Conference", new_conference_path %>
  </div>
</div>

<div class="container">
  <% @conferences.each do |c| %>
    <div class="col-sm-3">
      <div class="thumbnail">
        <%= link_to conference_path(c) do %>
          <%= c.title %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/conferences/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <legend>New Conference</legend>  
  <%= form_for @conference do |f| %>
    <div class="form-group">
      <label for="title">Title</label>
      <%= f.text_field :title, class:"form-control" %>      
    </div>
    <div class="form-group">
      <label for="desc">Description</label>
      <%= f.text_area :desc, class:'form-control' %>      
    </div>
    <div class="text-right">
      <%= f.submit class:'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/conferences/show.html.erb
<div class="jumbotron">
  <div class="container text-right">
    <h2><%= @conference.title %></h2>
    <div class="lead"><%= @conference.desc %></div>
  </div>
</div>

<div class="container">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="text-right">
      <%= link_to "New Event", new_conference_event_path(@conference), class:"btn btn-danger" %>
    </div>
    <hr>
    <div class="list-group">
      <% @conference.events.each do |e| %>
        <li class="list-group-item"><%= e.title %></li>
      <% end %>
    </div>    
  </div>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <legend>New Event</legend>  
  <%= form_for [@conference, @event] do |f| %>
    <div class="form-group">
      <label for="title">Title</label>
      <%= f.text_field :title, class:"form-control" %>      
    </div>
    <div class="form-group">
      <label for="desc">Description</label>
      <%= f.text_area :desc, class:'form-control' %>      
    </div>
    <div class="text-right">
      <%= f.submit class:'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unconf</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>